packages:
  - "apps/*"
  - "packages/*"

autoInstallPeers: true
strictPeerDependencies: false
confirmModulesPurge: false
publicHoistPattern:
  - "*prisma*"
  - "*eslint*"
  - "*prettier*"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
